### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by humleflue**
Clarified how to run your brainfuck program after a successful make-build.

### CODE REVIEW

**Review by rien333 — CHANGES_REQUESTED** [review]
> you run your Brainfuck program _from the build-dir_ with the following command:

You can actually run the binary from anywhere, as long as you put it in your $PATH. At the very least, I would word this differently. Or perhaps modify the compilation process to support `make install`.

Also, what you're describing is documented in the man page and the help output (`-h`).  Because both the man page and the help output are so short, it may also be a good idea to include those verbatim in the README.

**Comment by fabianishere** [comment]
Hi @humleflue, thank you for your contribution. It might indeed be helpful to clarify what to do after the make-build is successful. However, I agree with @rien333's comment. Let's see how we can proceed!

@rien333 
The help output is already in the README in the usage section and as far as I know, the compilation process also supports `make install`. Any suggestions on what do to else? Perhaps elaborate how to install the binaries on your system?

**Comment by humleflue** [comment]
I just struggled with figuring this out myself, so I thought it could be clearer. I just don't think the guidelines are as linear as they could be, if that makes sense? Feel free to rephrase my suggestion as you please :)

**Review by fabianishere — APPROVED** [review]

**Comment by fabianishere** [comment]
@humleflue I have reworded your changes a bit and added an example for installing the interpreter. Does this clarify the guidelines for you?

**Pull request merged**
