### PR TITLE
Toggle editline build and include option to build a shared library

### LINKED ISSUE #48: Add option to build shared library
We should add a CMake option to build a shared library for the project.

### PR DESCRIPTION
**Pull request by rien333**
Commit aa086188f1464e81f2d74b2bb1fca29a31d11d95 allows building a shared library per the request of https://github.com/Homebrew/homebrew-core/pull/17230#pullrequestreview-58672467 (closes #48)

Commit 47b639d47ac0a379b5483e2b29d251d247b9ea27 should close issue https://github.com/fabianishere/brainfuck/issues/43.

### CODE REVIEW

**Comment by fabianishere** [comment]
Awesome! Will take a look at it as soon as I have access to my computer.

**Comment by fabianishere** [comment]
I have separated both changes. #49 will allow building a shared library. Waiting on your feedback for the other change.

**Comment by rien333** [comment]
Sorry, I had  unintentionally left my debugging flags on in the commit.

**Comment by fabianishere** [comment]
#51 adds the option to toggle building with `editline` support.

**Pull request closed without merging**
